# Generated by Django 4.2.3 on 2024-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=20)),
                ('Seats', models.CharField(max_length=2)),
                ('Image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
