# Generated by Django 4.2.3 on 2024-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Phoneno', models.CharField(max_length=30)),
                ('boarding', models.CharField(max_length=30)),
                ('drop', models.CharField(max_length=30)),
                ('date_of_travel', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
