# Generated by Django 4.2.3 on 2024-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
